### ISSUE TITLE
Importing 3D models

### ISSUE THREAD

**Issue by VenomMeme** [m-x-d/GZDoom-Builder#23]
I'm working on a map for a project in my culinary class (hear me out). I made a 3D model and I don't know how to import my model. I converted it into an md2 and it still doesn't work.

**Comment by Ozymandias81** [comment]
What do you mean exactly with "import"? On GZDB you can "import" portions of maps as .obj models, so you probably mean to "include a new actor which uses an .md2 model"
To see your .md3 model working on GZDB, you have to code a bit, learning basics of Doom modding.

You need:
A) Learn how to create a simple .pk3 structure following [these rules](https://zdoom.org/wiki/Using_ZIPs_as_WAD_replacement)
B) A [modeldef lump](https://zdoom.org/wiki/MODELDEF), with proper names for model skins
C) An actor defined through [decorate](https://zdoom.org/wiki/DECORATE) or [zscript](https://zdoom.org/wiki/ZScript) (but since you don't seem expert go for decorate)

Also you must know that these builds of GZDB are outdated and discontinued since MaxED has left this project since January 2017, so you should try [these builds made by ZZYZX](http://devbuilds.drdteam.org/gzdbbf/), or check [GitHUB development](https://github.com/jewalky/GZDoom-Builder-Bugfix) for help

**Comment by VenomMeme** [comment]
Nevermind. I already scrapped the 3D model. But I got an A on the project.
